language: php

cache:
    directories:
        - $HOME/.composer/cache/files

env:
    global:
        - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)

matrix:
    fast_finish: true
    include:
        - php: 7.2
          env: LARAVEL_VERSION=~6.0  TESTBENCH_VERSION=~4.0  PHPUNIT_VERSION=~8.0
        - php: 7.2
          env: LARAVEL_VERSION=~7.0  TESTBENCH_VERSION=~5.0  PHPUNIT_VERSION=~8.0

        - php: 7.3
          env: LARAVEL_VERSION=~6.0  TESTBENCH_VERSION=~4.0  PHPUNIT_VERSION=~8.0
        - php: 7.3
          env: LARAVEL_VERSION=~7.0  TESTBENCH_VERSION=~5.0  PHPUNIT_VERSION=~8.0
        - php: 7.3
          env: LARAVEL_VERSION=~7.0  TESTBENCH_VERSION=~5.0  PHPUNIT_VERSION=~9.0
        - php: 7.3
          env: LARAVEL_VERSION=~8.0  TESTBENCH_VERSION=~6.0  PHPUNIT_VERSION=~9.0

        - php: 7.4
          env: LARAVEL_VERSION=~6.0  TESTBENCH_VERSION=~4.0  PHPUNIT_VERSION=~8.0
        - php: 7.4
          env: LARAVEL_VERSION=~7.0  TESTBENCH_VERSION=~5.0  PHPUNIT_VERSION=~9.0
        - php: 7.4
          env: LARAVEL_VERSION=~8.0  TESTBENCH_VERSION=~6.0  PHPUNIT_VERSION=~9.0

before_install:
    - travis_retry composer self-update
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

install:
    - composer require "illuminate/contracts:${LARAVEL_VERSION}" --no-update --no-interaction --prefer-dist
    - composer require "illuminate/support:${LARAVEL_VERSION}" --no-update --no-interaction --prefer-dist
    - composer require "orchestra/testbench:${TESTBENCH_VERSION}" --no-update --no-interaction --prefer-dist
    - composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --no-update --no-interaction --prefer-dist
    - travis_retry composer install --no-interaction --prefer-dist --no-suggest

script:
    - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_script:
    - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi

branches:
    only:
        - master

notifications:
    email: false
